// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TestShopApp.Infrastructure;

#nullable disable

namespace TestShopApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251127163606_TgFirstNameAndLastName")]
    partial class TgFirstNameAndLastName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TestShopApp.Common.Data.Group", b =>
                {
                    b.Property<string>("Number")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "number");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "createdAt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<long>("OwnerId")
                        .HasColumnType("bigint")
                        .HasAnnotation("Relational:JsonPropertyName", "ownerId");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "updatedAt");

                    b.HasKey("Number");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("TestShopApp.Common.Data.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "createdAt");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "firstName");

                    b.Property<string>("GroupNumber")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "groupNumber");

                    b.Property<string>("HeadmanOf")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "headmanOf");

                    b.Property<string>("LanguageCode")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "languageCode");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "lastName");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "photoUrl");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "role");

                    b.Property<string>("Subject")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "subject");

                    b.Property<string>("TgFirstName")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "tgFirstName");

                    b.Property<string>("TgLastName")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "tgLastName");

                    b.Property<string>("ThirdName")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "thirdName");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "updatedAt");

                    b.Property<string>("Username")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "username");

                    b.HasKey("Id");

                    b.HasIndex("GroupNumber");

                    b.HasIndex("HeadmanOf")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TestShopApp.Common.Data.User", b =>
                {
                    b.HasOne("TestShopApp.Common.Data.Group", "Group")
                        .WithMany("Students")
                        .HasForeignKey("GroupNumber")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TestShopApp.Common.Data.Group", null)
                        .WithOne()
                        .HasForeignKey("TestShopApp.Common.Data.User", "HeadmanOf")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Group");
                });

            modelBuilder.Entity("TestShopApp.Common.Data.Group", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
